stages:
- develop
- master

deploy:
  stage: develop
  script:
  - whoami
  - if [ $CI_COMMIT_REF_NAME = 'develop' ]; then
  - rm -Rf ~/testdeploy/
  - mkdir ~/testdeploy/
  - cd ~/testdeploy/
  - rm -Rf repository/
  - rm -Rf site/
  - mkdir repository
  - mkdir site
  - git clone --mirror git@gitlab.com:https://gitlab.com/kbc-itw/smile-cycle/ ./repository
  - cd ./repository
  - git --work-tree=../site/ checkout -f develop
  - cd ../site/
  - rsync -rlOzv --delete --checksum ./ /home/src
  - cd /home/src
  - else
  - echo 'develop以外なので何もしない'
  - fi
  tags:
  - testdeploy