stages:
- develop

deploy:
  stage: develop
  script:
  - if [ $CI_COMMIT_REF_NAME = 'develop' ]; then
  - rm -Rf ~/testdeploy/
  - mkdir ~/testdeploy/
  - cd ~/testdeploy/
  - rm -Rf repository/
  - rm -Rf site/
  - mkdir repository
  - mkdir site
  - git clone --mirror git@gitlab.com:kbc-itw/smile-cycle ./repository
  - cd ./repository
  - git --work-tree=../site/ checkout -f develop
  - cd ../site/
  - rsync -rlOzv --delete --checksum ./ /home/kbcadminstudent/
  - cd /home/kbcadminstudent/
  - else
  - echo 'エラーです'
  - fi
  tags:
  - testdeploy
   only:
  - merge_requests
