version: '3.7'
services:
    node:
        image: node
        environment:
          DEBUG_DEPTH: "2"
          DEBUG_COLORS: "true"
          DEBUG_HIDE_DATE: "false"
        ports:
          - "3000:3000"
          - "8080:8080"
        volumes:
          - "./workspace:/app"
        working_dir: /app
        tty: true
    mongo:
        image: mongo
        restart: always
        volumes:
          - ./mongo/data:/data
        ports:
          - "27017:27017"
        tty: true
        environment:
          - MONGO_INITDB_DATABASE=test